resources:
  - deployment.yml
  - service.yml

commonLabels:
  app: kustomwebapp

commonAnnotations:
  app: mykustom-annotations

namePrefix: kustom-
nameSuffix: -v1

configMapGenerator:
  - name: mykustom-map
    envs:
      - config.properties